### ISSUE TITLE
Announcement Copy command is failing.

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#59]
## *Who* is the bug affecting?
Anyone inputting the `!a copy` command

## *What* is affected by this bug?
The bot

## *When* does this occur?
When the `!a copy [announcementID]` command is used

## *Where* on the platform does it happen?
Discord bot interface

## *How* do we replicate the issue?
Try to copy an announcement

## Expected behavior (i.e. solution)
Bot should have created a copy of 

## Other Comments
Exception
java.lang.NullPointerException: defaultValue
at java.util.Objects.requireNonNull(Objects.java:228)
at reactor.core.publisher.MonoDefaultIfEmpty.<init>(MonoDefaultIfEmpty.java:32)
at reactor.core.publisher.Mono.defaultIfEmpty(Mono.java:2012)
at org.dreamexposure.discal.client.announcement.AnnouncementCreator.init(AnnouncementCreator.java:72)
at org.dreamexposure.discal.client.module.command.AnnouncementCommand.lambda$moduleCopy$156(AnnouncementCommand.java:1395)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
at reactor.core.publisher.MonoHasElement$HasElementSubscriber.onNext(MonoHasElement.java:74)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:162)
at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
at reactor.core.publisher.FluxHandle$HandleSubscriber.onN
Shard Index
11
Class
org.dreamexposure.discal.client.listeners.discord.MessageCreateListener
Time
07-09-2020-06.06.20
Message
Error Handling message event
Info
!!a copy 73ec5efa-f675-417e-aefc-9730209615b6
Today at 02:06

**Comment by NovaFox161** [comment]
I've removed the offending code causing the error which results in the bot "ignoring" the user's message. However, I am looking into this deeper because that error shouldn't actually be happening. Apparently the database check to see if the announcement exists works, but then calling that again to actually load that information into memory isn't working specifically when attempting to copy (very similar code is working for editing announcements, not sure why its different here...)

**Comment by NovaFox161** [comment]
Nvm, apparently it just works now. Closing issue as fixed. Will be deployed for the 4.1.0 release milestone.
