### ISSUE TITLE
Events creation can't be confirmed

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#63]
## *Who* is the bug affecting?
Admins creating events

## *What* is affected by this bug?
The bot

## *When* does this occur?
When using the event creation wizard, the bot fails at the `!e confirm` step

## *Where* on the platform does it happen?
Event creation wizard

## *How* do we replicate the issue?
Create an event and try to confirm it.

## Expected behavior (i.e. solution)
Event should have been confirmed

## Other Comments
**Exception**
java.lang.NullPointerException
at org.dreamexposure.discal.client.event.EventCreator.lambda$confirmEvent$18(EventCreator.java:172)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:249)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Shard Index
14
Class
org.dreamexposure.discal.client.listeners.discord.MessageCreateListener
Time
09-09-2020-05.44.54
Message
Error Handling message event
Info
!event confirm
Today at 13:44

**Comment by smnc** [comment]
I've been unable to replicate this. I've tried in multiple servers on 3 different shards, on both internal and external calendars.

**Comment by NovaFox161** [comment]
I couldn't replicate either, however I did look into the logs and believe its an edge case causing the bug. I've change some of the code in section that the error is occurring at. Should be able to handle a null value now (even tho it shouldn't even be possible for it to be null)
